GET http://localhost:3333/genres
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTBjZjdmZTdiYmYzNTQ0MmQwZGQxMyIsIm5hbWUiOiJUZXN0ZSB0ZXN0ZSIsImVtYWlsIjoidGVzdGUxQHRlc3RlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA4JDdMbWQvUmpMTjJ0Z0ZvVHdIMmg1NGVnMXVzVnM5bmZ1WWRhYy5YM1ZIT0lCVUxnQkxvaGdTIiwidXNlcm5hbWUiOiJAdGVzdGUxNzA5MjMxOTk5MDE2IiwiYmlvIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMi0yOVQxODozOTo1OS4wMzRaIiwidXBkYXRlZEF0IjoiMjAyNC0wMi0yOVQxODozOTo1OS4wMzRaIiwiaWF0IjoxNzA5MzMwOTM2LCJleHAiOjE3MDk5MzU3MzZ9.GcJ60JxJa1RsXohWgDVP8oWLJCKxDKyJwOqYmyqwx78

###
GET http://localhost:3333/genres/65e22c5ee67ec4a7d10f9687
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTBjZjdmZTdiYmYzNTQ0MmQwZGQxMyIsIm5hbWUiOiJUZXN0ZSB0ZXN0ZSIsImVtYWlsIjoidGVzdGUxQHRlc3RlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA4JDdMbWQvUmpMTjJ0Z0ZvVHdIMmg1NGVnMXVzVnM5bmZ1WWRhYy5YM1ZIT0lCVUxnQkxvaGdTIiwidXNlcm5hbWUiOiJAdGVzdGUxNzA5MjMxOTk5MDE2IiwiYmlvIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMi0yOVQxODozOTo1OS4wMzRaIiwidXBkYXRlZEF0IjoiMjAyNC0wMi0yOVQxODozOTo1OS4wMzRaIiwiaWF0IjoxNzA5MzMwOTM2LCJleHAiOjE3MDk5MzU3MzZ9.GcJ60JxJa1RsXohWgDVP8oWLJCKxDKyJwOqYmyqwx78

###
POST http://localhost:3333/genres
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTBjZjdmZTdiYmYzNTQ0MmQwZGQxMyIsIm5hbWUiOiJUZXN0ZSB0ZXN0ZSIsImVtYWlsIjoidGVzdGUxQHRlc3RlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA4JDdMbWQvUmpMTjJ0Z0ZvVHdIMmg1NGVnMXVzVnM5bmZ1WWRhYy5YM1ZIT0lCVUxnQkxvaGdTIiwidXNlcm5hbWUiOiJAdGVzdGUxNzA5MjMxOTk5MDE2IiwiYmlvIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMi0yOVQxODozOTo1OS4wMzRaIiwidXBkYXRlZEF0IjoiMjAyNC0wMi0yOVQxODozOTo1OS4wMzRaIiwiaWF0IjoxNzA5MzMwOTM2LCJleHAiOjE3MDk5MzU3MzZ9.GcJ60JxJa1RsXohWgDVP8oWLJCKxDKyJwOqYmyqwx78

{
  "gender": "Romance"
}

###
PATCH http://localhost:3333/genres/65e252a77235935886dc7cdc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTBjZjdmZTdiYmYzNTQ0MmQwZGQxMyIsIm5hbWUiOiJUZXN0ZSB0ZXN0ZSIsImVtYWlsIjoidGVzdGUxQHRlc3RlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA4JDdMbWQvUmpMTjJ0Z0ZvVHdIMmg1NGVnMXVzVnM5bmZ1WWRhYy5YM1ZIT0lCVUxnQkxvaGdTIiwidXNlcm5hbWUiOiJAdGVzdGUxNzA5MjMxOTk5MDE2IiwiYmlvIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMi0yOVQxODozOTo1OS4wMzRaIiwidXBkYXRlZEF0IjoiMjAyNC0wMi0yOVQxODozOTo1OS4wMzRaIiwiaWF0IjoxNzA5MzMwOTM2LCJleHAiOjE3MDk5MzU3MzZ9.GcJ60JxJa1RsXohWgDVP8oWLJCKxDKyJwOqYmyqwx78

{
  "gender": "Gastronomia"
}

###
DELETE http://localhost:3333/genres/65e252a77235935886dc7cdc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTBjZjdmZTdiYmYzNTQ0MmQwZGQxMyIsIm5hbWUiOiJUZXN0ZSB0ZXN0ZSIsImVtYWlsIjoidGVzdGUxQHRlc3RlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA4JDdMbWQvUmpMTjJ0Z0ZvVHdIMmg1NGVnMXVzVnM5bmZ1WWRhYy5YM1ZIT0lCVUxnQkxvaGdTIiwidXNlcm5hbWUiOiJAdGVzdGUxNzA5MjMxOTk5MDE2IiwiYmlvIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMi0yOVQxODozOTo1OS4wMzRaIiwidXBkYXRlZEF0IjoiMjAyNC0wMi0yOVQxODozOTo1OS4wMzRaIiwiaWF0IjoxNzA5MzMwOTM2LCJleHAiOjE3MDk5MzU3MzZ9.GcJ60JxJa1RsXohWgDVP8oWLJCKxDKyJwOqYmyqwx78