#rest client

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Teste teste",
  "email": "teste2@teste.com",
  "password": "@Teste123",
  "confirmPassword": "@Teste123"
}


### 
GET http://localhost:3333/users

### 
GET http://localhost:3333/users/65e0ce538963b880c151ec355
