#rest client

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Teste teste",
  "email": "teste10@teste.com",
  "password": "@Teste123",
  "confirmPassword": "@Teste123"
}


### 
GET http://localhost:3333/users


###
PATCH http://localhost:3333/users/65e0ce538963b880c151ec35
Content-Type: application/json

{
  "name": "MARIA SILVA SANTOS",
  "email": "mariasilva@teste.com",
  "password": "@Teste1234",
  "confirmPassword": "@Teste1234"
}

### 
GET http://localhost:3333/users/65e0ce538963b880c151ec35
