GET http://localhost:3333/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTYxZTNhNzVmMTFiMDAzOGJmZjdkYyIsIm5hbWUiOiJBbGZyZWRvIFNvdXNhIEFtb3JpbSIsImVtYWlsIjoiYWxmcmVkb2Ftb3JpbUBlbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCR1MEZjam9KMTAuL2w1MjJZajNDNUFlVERRYWQ0ajRKdE50alo0eDZCODlOcWVUU0p0dUpCQyIsInVzZXJuYW1lIjoiQGFsZnJlZG8xNzA5NTc5ODM0OTA3IiwiYmlvIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMy0wNFQxOToxNzoxNC45NDRaIiwidXBkYXRlZEF0IjoiMjAyNC0wMy0wNFQyMDozNToxNC44MjJaIiwiaWF0IjoxNzA5NTkwNzk5LCJleHAiOjE3MTAxOTU1OTl9.Uxi1BJ1GkOfEG9c2OgJEgDxDzJMPJg01eJjTKL7xDlg

###
GET http://localhost:3333/comments/65e64811aff572a07d1e8331
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTYxZTNhNzVmMTFiMDAzOGJmZjdkYyIsIm5hbWUiOiJBbGZyZWRvIFNvdXNhIEFtb3JpbSIsImVtYWlsIjoiYWxmcmVkb2Ftb3JpbUBlbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCR1MEZjam9KMTAuL2w1MjJZajNDNUFlVERRYWQ0ajRKdE50alo0eDZCODlOcWVUU0p0dUpCQyIsInVzZXJuYW1lIjoiQGFsZnJlZG8xNzA5NTc5ODM0OTA3IiwiYmlvIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMy0wNFQxOToxNzoxNC45NDRaIiwidXBkYXRlZEF0IjoiMjAyNC0wMy0wNFQyMDozNToxNC44MjJaIiwiaWF0IjoxNzA5NTkyMzIxLCJleHAiOjE3MTAxOTcxMjF9.ACAi67VrZ5nj2_3EVWtKfiq2Efi_lvQ2WQn3sgEdKNQ

###
POST http://localhost:3333/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTYxZTNhNzVmMTFiMDAzOGJmZjdkYyIsIm5hbWUiOiJBbGZyZWRvIFNvdXNhIEFtb3JpbSIsImVtYWlsIjoiYWxmcmVkb2Ftb3JpbUBlbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCR1MEZjam9KMTAuL2w1MjJZajNDNUFlVERRYWQ0ajRKdE50alo0eDZCODlOcWVUU0p0dUpCQyIsInVzZXJuYW1lIjoiQGFsZnJlZG8xNzA5NTc5ODM0OTA3IiwiYmlvIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMy0wNFQxOToxNzoxNC45NDRaIiwidXBkYXRlZEF0IjoiMjAyNC0wMy0wNFQyMDozNToxNC44MjJaIiwiaWF0IjoxNzA5NTkyMzIxLCJleHAiOjE3MTAxOTcxMjF9.ACAi67VrZ5nj2_3EVWtKfiq2Efi_lvQ2WQn3sgEdKNQ

{
  "text": "Livro muito legal e interessante feito com muito carinho que conta uma história encantadora",
  "bookGrade": 5.0,
  "bookId": "65e63e193d8c4fc84ca5aaaf"
}

###
PATCH http://localhost:3333/comments/65e73d9d7b49da78ec374dd0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTYxZTNhNzVmMTFiMDAzOGJmZjdkYyIsIm5hbWUiOiJBbGZyZWRvIFNvdXNhIEFtb3JpbSIsImVtYWlsIjoiYWxmcmVkb2Ftb3JpbUBlbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCR1MEZjam9KMTAuL2w1MjJZajNDNUFlVERRYWQ0ajRKdE50alo0eDZCODlOcWVUU0p0dUpCQyIsInVzZXJuYW1lIjoiQGFsZnJlZG8xNzA5NTc5ODM0OTA3IiwiYmlvIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMy0wNFQxOToxNzoxNC45NDRaIiwidXBkYXRlZEF0IjoiMjAyNC0wMy0wNFQyMDozNToxNC44MjJaIiwiaWF0IjoxNzA5NTkyMzIxLCJleHAiOjE3MTAxOTcxMjF9.ACAi67VrZ5nj2_3EVWtKfiq2Efi_lvQ2WQn3sgEdKNQ

{
  "text": "Comentário de um livro muito interessante que conta uma história encantadora",
  "bookGrade": 4.5,
  "bookId": "65e63e193d8c4fc84ca5aaaf"
}

###
DELETE http://localhost:3333/comments/65e73d9d7b49da78ec374dd0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTYxZTNhNzVmMTFiMDAzOGJmZjdkYyIsIm5hbWUiOiJBbGZyZWRvIFNvdXNhIEFtb3JpbSIsImVtYWlsIjoiYWxmcmVkb2Ftb3JpbUBlbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCR1MEZjam9KMTAuL2w1MjJZajNDNUFlVERRYWQ0ajRKdE50alo0eDZCODlOcWVUU0p0dUpCQyIsInVzZXJuYW1lIjoiQGFsZnJlZG8xNzA5NTc5ODM0OTA3IiwiYmlvIjpudWxsLCJpbWFnZVVybCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMy0wNFQxOToxNzoxNC45NDRaIiwidXBkYXRlZEF0IjoiMjAyNC0wMy0wNFQyMDozNToxNC44MjJaIiwiaWF0IjoxNzA5NTkyMzIxLCJleHAiOjE3MTAxOTcxMjF9.ACAi67VrZ5nj2_3EVWtKfiq2Efi_lvQ2WQn3sgEdKNQ